---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: harbor-microscanner-adapter
spec:
  template:
    metadata:
      labels:
        app: harbor-microscanner-adapter
    spec:
      containers:
        - name: main
          image: aquasec/harbor-microscanner-adapter:poc
          imagePullPolicy: IfNotPresent
          env:
            - name: "ADAPTER_ADDR"
              value: ":8080"
            - name: "ADAPTER_DOCKER_HOST"
              value: "tcp://localhost:2375"
            - name: "ADAPTER_REGISTRY_URL"
              value: "core.harbor.domain"
            - name: "ADAPTER_MICRO_SCANNER_OPTIONS"
              value: "-c"
            - name: "ADAPTER_MICRO_SCANNER_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: harbor-microscanner-adapter
                  key: microscanner-token
          ports:
            - containerPort: 8080
        - name: dind
          image: docker:18.05-dind
          imagePullPolicy: IfNotPresent
          env:
            - name: "DOCKER_HOST"
              value: "tcp://localhost:2375"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
            - name: dind-config
              mountPath: /etc/docker/certs.d/core.harbor.domain
              readOnly: true
      volumes:
        - name: dind-storage
          emptyDir: {}
        - name: dind-config
          secret:
            secretName: harbor-microscanner-adapter-dind
---
apiVersion: v1
kind: Service
metadata:
  name: harbor-microscanner-adapter
spec:
  selector:
    app: harbor-microscanner-adapter
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
