version: '3'

networks:
  scanner:
    driver: bridge

services:
  scanner:
    image: aquasec/harbor-scanner-microscanner:poc
    environment:
      SCANNER_API_ADDR: ":8080"
      SCANNER_DOCKER_HOST: "tcp://dind:2375"
      SCANNER_MICROSCANNER_TOKEN: ${SCANNER_MICROSCANNER_TOKEN}
      SCANNER_MICROSCANNER_OPTIONS: "--continue-on-failure"
      SCANNER_STORE_DRIVER: "redis"
      SCANNER_STORE_REDIS_URL: "redis://redis:6379"
      SCANNER_JOB_QUEUE_REDIS_URL: "redis://redis:6379"
    networks:
      - scanner
    ports:
      - 8080:8080
    volumes:
      - scanner-data:/data/scanner
  dind:
    image: docker:18.05-dind
    privileged: true
    environment:
      DOCKER_HOST: "tcp://localhost:2375"
    networks:
      - scanner
    volumes:
      - dind-data:/var/lib/docker
  redis:
    image: redis:5.0.5
    ports:
      - 6379:6379
    networks:
      - scanner

volumes:
  scanner-data:
  dind-data:
